services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
      - ./InitScripts:/init 
#    restart: always
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-U", "sa", "-P", "Password123", "-Q", "SELECT 1", "-C"]
    entrypoint:
        - "/bin/bash"
        - "init/entrypoint.sh"
volumes:
  mssql-data:
    driver: local
